### ISSUE TITLE
The mapping of vocab should start from zero, or else embedding index would overflow

### ISSUE THREAD

**Issue by thunderbird2009** [minqukanq/hierarchical-multi-label-text-classification#7]
https://github.com/minqukanq/hierarchical-multi-label-text-classification/blob/1cf4b019231cccdb77555f0d717770a8787e34e5/utils/data_helper.py#L14

Should it be changed to:
vocab_to_int = {word: ii for ii, word in enumerate(vocab)}

**Comment by minqukanq** [comment]
Thanks for your contribution.
I updated it.
